
const gt = globalThis as any;

export const GLOBAL_PARAMS = {

    GRAND_BAZAAR_RANGE: 1,

    MARKETS_REFRESH_PERIOD_MULTI: 1,
    MARKETS_ALWAYS_DIFFERENT_TRADES: false,
    MARKETS_STORAGE_MULTI: 1,
    MARKETS_BASE_SELL_AMOUNT_MULTI: 1,

    CARAVANSARIES_STORAGE_MULTI: 1,

    WAREHOUSES_STORAGE_MULTI: 1,

    HAPPINESS_MIN_CAP: -50,
    HAPPINESS_MAX_CAP: 50,

    SWISS_BANK_MULTI: 1,
    SWISS_BANK_USES_CARAVANS: false,

    FIXES_DECAY_BUILDING_PERCENTAGE: 0.99,


};
gt.GLOBAL_PARAMS = GLOBAL_PARAMS;
